#!/usr/bin/env python3
"""Generate emoji_categories.inc (the picker's categories) from iamcal/emoji-data.

    curl -sL https://raw.githubusercontent.com/iamcal/emoji-data/3cf4d12c20b15ecdc53215b6b625b8515117aa93/emoji.json \\
        -o /tmp/emoji-data.json
    python3 src/app/mrkdwn/gen_emoji_categories.py /tmp/emoji-data.json

The committed table comes from emoji-data commit 3cf4d12 (twemoji v16.0.1);
a newer emoji.json reorders some names and changes some skin-tone flags.

The picker shows eight categories in emoji-data's canonical order (its
sort_order; Smileys & Emotion and People & Body merged into one tab, like
Slack). Each emoji is listed under the first of its short names that the
shortcode table (scripts/emoji_table.json) resolves, so the picker never shows
a ":name:" fallback. Every name is re-indexed into the sorted shortcode table
(emoji_table.inc, same order as gen_emoji_table.py), so a category is a uint16
run and the skin-tone flag one bit per shortcode: set for every resolvable
alias of an emoji with single-modifier (Fitzpatrick) skin variations.
"""
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, '..', '..', '..'))
TABLE = os.path.join(ROOT, 'scripts', 'emoji_table.json')
OUT = os.path.join(HERE, 'emoji_categories.inc')

# emoji-data category -> picker category (id, label), in tab order.
CATEGORIES = {
    'Smileys & Emotion': ('people', 'Smileys & people'),
    'People & Body': ('people', 'Smileys & people'),
    'Animals & Nature': ('nature', 'Animals & nature'),
    'Food & Drink': ('food', 'Food & drink'),
    'Travel & Places': ('travel', 'Travel & places'),
    'Activities': ('activity', 'Activities'),
    'Objects': ('objects', 'Objects'),
    'Symbols': ('symbols', 'Symbols'),
    'Flags': ('flags', 'Flags'),
}
ORDER = ['people', 'nature', 'food', 'travel', 'activity', 'objects', 'symbols', 'flags']


def main():
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    data = json.load(open(sys.argv[1], encoding='utf-8'))
    table = json.load(open(TABLE, encoding='utf-8'))
    order = sorted(table, key=lambda s: s.encode())
    index = {n: i for i, n in enumerate(order)}
    members = {cid: [] for cid in ORDER}
    labels = {}
    skin = set()
    for e in data:
        if e.get('category') not in CATEGORIES:
            continue
        cid, label = CATEGORIES[e['category']]
        labels[cid] = label
        name = next((n for n in e['short_names'] if n in index), None)
        if name is None:
            continue
        members[cid].append((e['sort_order'], name))
        if any(re.fullmatch(r'1F3F[B-F]', k) for k in (e.get('skin_variations') or {})):
            skin.update(n for n in e['short_names'] if n in index)
    runs, defs = [], []
    for cid in ORDER:
        seen = set()
        idx = []
        for _, n in sorted(members[cid]):
            if n not in seen:
                seen.add(n)
                idx.append(index[n])
        defs.append((cid, labels[cid], len(runs), len(idx)))
        runs += idx
    bits = bytearray((len(order) + 7) // 8)
    for n in skin:
        bits[index[n] // 8] |= 1 << (index[n] % 8)
    with open(OUT, 'w', encoding='utf-8') as f:
        f.write('// Generated by gen_emoji_categories.py from iamcal/emoji-data — do not edit.\n')
        f.write('struct EmojiCategory {\n    const char *id, *label;\n    unsigned short first, count;\n};\n')
        f.write('static const EmojiCategory kEmojiCategories[] = {\n')
        for cid, label, first, n in defs:
            f.write(f'    {{"{cid}", N_("{label}"), {first}, {n}}},\n')  # tr() in categoryLabel
        f.write('};\n')
        f.write('static const unsigned short kEmojiCategoryNames[] = {\n')
        for k in range(0, len(runs), 16):
            f.write('    ' + ','.join(str(x) for x in runs[k:k + 16]) + ',\n')
        f.write('};\n')
        f.write('static const unsigned char kEmojiSkinBits[] = {\n')
        for k in range(0, len(bits), 24):
            f.write('    ' + ','.join(str(x) for x in bits[k:k + 24]) + ',\n')
        f.write('};\n')
    print(f'{OUT}: {len(defs)} categories, {len(runs)} names', file=sys.stderr)


if __name__ == '__main__':
    main()
