#!/usr/bin/env python3
"""Generate emoji_categories.inc (the picker's categories) from the emoji catalog.

    python3 src/app/mrkdwn/gen_emoji_categories.py        # from the repo root

The picker shows eight categories in iamcal/emoji-data's canonical order,
generated into src/util/emoji_data.cpp by scripts/gen-emoji-catalog.py. This
reads that file (its kEntries names, flags and kCat_* index arrays) and
re-indexes every name into the sorted shortcode table (emoji_table.inc,
same order as gen_emoji_table.py), so a category is a uint16 run and the
skin-tone flag one bit per shortcode.
"""
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, '..', '..', '..'))
CATALOG = os.path.join(ROOT, 'src', 'util', 'emoji_data.cpp')
TABLE = os.path.join(ROOT, 'scripts', 'emoji_table.json')
OUT = os.path.join(HERE, 'emoji_categories.inc')


def main():
    src = open(CATALOG, encoding='utf-8').read()
    entries = re.findall(r'\{(\d+), (\d+), (\d+), (\d+)\}, // (\S+)', src)
    names = [e[4] for e in entries]
    flags = [int(e[3]) for e in entries]
    cats = re.findall(r'\{"(\w+)", "([^"]+)", kCat_(\w+), (\d+)\}', src)
    arrays = {m.group(1): [int(x) for x in m.group(2).split(',') if x.strip()]
              for m in re.finditer(r'static const quint16 kCat_(\w+)\[\] = \{([^}]*)\}', src)}
    table = json.load(open(TABLE, encoding='utf-8'))
    order = sorted(table, key=lambda s: s.encode())
    index = {n: i for i, n in enumerate(order)}
    runs, defs = [], []
    for cid, label, arr, count in cats:
        idx = [index[names[k]] for k in arrays[arr] if names[k] in index]
        defs.append((cid, label[:1] + label[1:].lower(), len(runs), len(idx)))  # sentence case
        runs += idx
    skin = bytearray((len(order) + 7) // 8)
    for n, f in zip(names, flags):
        if f & 1 and n in index:
            skin[index[n] // 8] |= 1 << (index[n] % 8)
    with open(OUT, 'w', encoding='utf-8') as f:
        f.write('// Generated by gen_emoji_categories.py from src/util/emoji_data.cpp — do not edit.\n')
        f.write('struct EmojiCategory {\n    const char *id, *label;\n    unsigned short first, count;\n};\n')
        f.write('static const EmojiCategory kEmojiCategories[] = {\n')
        for cid, label, first, n in defs:
            f.write(f'    {{"{cid}", N_("{label}"), {first}, {n}}},\n')  # tr() in categoryLabel
        f.write('};\n')
        f.write('static const unsigned short kEmojiCategoryNames[] = {\n')
        for k in range(0, len(runs), 16):
            f.write('    ' + ','.join(str(x) for x in runs[k:k + 16]) + ',\n')
        f.write('};\n')
        f.write('static const unsigned char kEmojiSkinBits[] = {\n')
        for k in range(0, len(skin), 24):
            f.write('    ' + ','.join(str(x) for x in skin[k:k + 24]) + ',\n')
        f.write('};\n')
    print(f'{OUT}: {len(defs)} categories, {len(runs)} names', file=sys.stderr)


if __name__ == '__main__':
    main()
