#!/usr/bin/env python3
"""Generate emoji_table.inc (Slack shortcode -> Unicode) from scripts/emoji_table.json.

    python3 src/app/mrkdwn/gen_emoji_table.py            # from the repo root

The table is looked up in place, never unpacked:

* names are sorted and front-coded (each entry stores how many leading bytes
  it shares with the previous name, then the rest); every 16th entry is a
  restart point that stores its full name, and a small index of restart
  offsets lets lookup binary-search the restarts and scan at most 16 entries.
* values are code points in a byte code tuned for emoji (see decodeValue in
  emoji.cpp): 1 byte for ZWJ, FE0F, skin tones, keycap, ASCII and regional
  indicators, 2 bytes for U+1Fxxx and U+2000-6FFF, 4 bytes otherwise.

Entry layout: shared(1) suffixLen(1) suffix valueLen(1) value.
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, '..', '..', '..'))
SRC = os.path.join(ROOT, 'scripts', 'emoji_table.json')
OUT = os.path.join(HERE, 'emoji_table.inc')
RESTART = 16


def encode_cp(cp: int) -> bytes:
    if cp == 0x200D:
        return b'\x10'
    if cp == 0xFE0F:
        return b'\x11'
    if 0x1F3FB <= cp <= 0x1F3FF:
        return bytes([0x12 + cp - 0x1F3FB])
    if cp == 0x20E3:
        return b'\x17'
    if 0x20 <= cp < 0x80:
        return bytes([cp])
    if 0x1F1E6 <= cp <= 0x1F1FF:
        return bytes([0x80 + cp - 0x1F1E6])
    if 0x1F000 <= cp <= 0x1FFFF:
        v = cp - 0x1F000
        return bytes([v >> 8, v & 0xFF])
    if 0x2000 <= cp <= 0x6FFF:
        v = cp - 0x2000
        return bytes([0xA0 + (v >> 8), v & 0xFF])
    return bytes([0xF0, (cp >> 16) & 0xFF, (cp >> 8) & 0xFF, cp & 0xFF])


def main():
    table = json.load(open(SRC, encoding='utf-8'))
    names = sorted(table, key=lambda s: s.encode())
    data = bytearray()
    restarts = []
    prev = b''
    utf8_bytes = 0
    for i, name in enumerate(names):
        n = name.encode()
        if i % RESTART == 0:
            restarts.append(len(data))
            shared = 0
        else:
            shared = 0
            while shared < min(len(n), len(prev), 255) and n[shared] == prev[shared]:
                shared += 1
        suffix = n[shared:]
        value = b''.join(encode_cp(ord(c)) for c in table[name])
        utf8_bytes += len(table[name].encode())
        assert len(suffix) < 256 and len(value) < 256
        data += bytes([shared, len(suffix)]) + suffix + bytes([len(value)]) + value
        prev = n
    assert len(data) < 65536, 'restart offsets are uint16'

    def c_bytes(b):
        lines = []
        for k in range(0, len(b), 20):
            lines.append('    ' + ','.join(str(x) for x in b[k:k + 20]) + ',')
        return '\n'.join(lines)

    with open(OUT, 'w', encoding='utf-8') as f:
        f.write('// Generated by gen_emoji_table.py from scripts/emoji_table.json — do not edit.\n')
        f.write(f'// {len(names)} shortcodes; {len(data)} bytes of entries + '
                f'{2 * len(restarts)} bytes of restart index\n')
        f.write(f'// (plain name/value strings would be {sum(len(n.encode()) for n in names) + utf8_bytes} bytes '
                f'+ {4 * len(names)} of offsets).\n')
        f.write(f'static constexpr int kEmojiCount = {len(names)};\n')
        f.write(f'static constexpr int kEmojiRestart = {RESTART};\n')
        f.write('static const unsigned char kEmojiData[] = {\n' + c_bytes(data) + '\n};\n')
        f.write('static const unsigned short kEmojiRestarts[] = {\n')
        for k in range(0, len(restarts), 12):
            f.write('    ' + ','.join(str(x) for x in restarts[k:k + 12]) + ',\n')
        f.write('};\n')
    print(f'{OUT}: {len(names)} entries, {len(data)} + {2 * len(restarts)} bytes', file=sys.stderr)


if __name__ == '__main__':
    main()
