// A settings file written by Qt 6's QSettings (IniFormat, the encoding of
// QSettings("msga", "msga") on Linux) with the keys and value shapes the old
// app stored: generated by a throwaway Qt program, not by hand, so the
// parser is checked against Qt's real output. Shared by the base tests
// (parsing) and the app tests (the import of the old settings).
#pragma once

namespace oldsettings_fixture {

inline constexpr char kIni[] = R"INI(
[General]
active=slack:T0123
storeVersion=2
workspaces=slack:T0123, claude-code:local, slack:T0456

[appearance]
customTheme="{\"brightness\":4,\"gradient\":false,\"highlight1\":{\"hex\":\"#112233\"},\"highlight2\":{\"hex\":\"#2BAC76\"},\"important\":{\"hex\":\"#CD2553\"},\"primary\":{\"hex\":\"#445566\",\"palette\":\"x\"},\"sidebarInverted\":false,\"useCustomHex\":true}"
fontSize=large
language=ja
mode=dark
relevantDays=30
showLinkPreviews=false
theme=blue
themeDark=custom
threadsInline=true
timeFormat=12h

[claudeCode]
lastDir=/home/u/src
lastDir\architect=/home/u/src/a b
recentDirs\1\path=/home/u/src
recentDirs\1\usedAt=1767225000
recentDirs\2\path="/home/u/x,y"
recentDirs\2\usedAt=1767224000
recentDirs\size=2

[composer]
ctrlEnterSends=true
spellCheck=true
spellLanguages=en_US, de_DE

[conv]
visitedAt={\"C1\":1767225600}

[credentials]
slackClientId=123.456
slackClientSecret=sec\"ret\\x
slackXapp=xapp-1-A

[emoji]
recent=thumbsup, heart
skinTone=3

[gif]
giphy\apiKey=@@giphy

[llm]
anthropic\apiKey=sk-ant-1
custom-ab12cd34\apiKey=k2
customProviders=custom-ab12cd34
defaultProvider=custom-ab12cd34
nativeLanguage=sv
providers\anthropic\model=claude-x
providers\custom-ab12cd34\baseUrl=http://localhost:11434/v1
providers\custom-ab12cd34\model=llama
providers\custom-ab12cd34\name=Local
providers\custom-ab12cd34\sttModel=whisper-1

[multi]
line=a\nb\tc\x1\x64

[notifications]
defaultMigrated=true
enabled=true
level=1
soundId=system:Glass

[presence]
mode=using

[slack]
connectionMode=appkeys

[spaces]
lead=" padded "

[storage]
cacheCapMb=500

[tray]
customIcon=true
customIconMonochrome=false

[updates]
autoCheck=false
lastChecked=1767225600

[voice]
cleanup=false
glossary=msga, "Kubernetes, k8s"

[window]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0_\0\0\0\x46\0\0\x5|\0\0\x3\xa1\0\0\0\x64\0\0\0\x64\0\0\x5w\0\0\x3\x97\0\0\0\0\0\0\0\0\n\0\0\0\0\x64\0\0\0\x64\0\0\x5w\0\0\x3\x97)
minimizeToTray=true
threadWidth=420

[workspace]
claude-code%3Alocal\displayName=Claude Code
slack%3AT0123\auth="{\"xoxp\":\"xoxc-1-2\",\"refreshToken\":\"\",\"expiresAt\":\"0\",\"cookie\":\"xoxd-a%2Fb=c;d\"}"
slack%3AT0123\customIcon=/home/u/.local/share/msga/MSGA/workspace_icons/slack_T0123-1700000000000.png
slack%3AT0123\displayName="Acme, Inc."
slack%3AT0123\iconUrl=https://a.slack-edge.com/x.png
slack%3AT0123\muted=true
slack%3AT0456\auth="{\"xoxp\":\"xoxp-9\",\"refreshToken\":\"xoxe-1\",\"expiresAt\":\"1767225600\"}"
slack%3AT0456\displayName=Ünïcödé 日本
)INI";

} // namespace oldsettings_fixture
