#!/usr/bin/env python3
"""Generates src/base/date_locales_generated.inc: month, weekday and AM/PM
names and the short numeric date pattern of common locales, from CLDR (via
Babel), for Linux builds of msga.

Windows and macOS ask the OS (GetLocaleInfoEx, CFDateFormatter); a static
Linux binary can't rely on glibc/musl locale data, so the CLDR data is
compiled in here, trimmed to the languages below.

    python3 src/tools/date_locales.py      (needs `pip install babel`)

Format (one string literal, NUL-separated, no pointers):
  per language:  code, 12 months, 12 short months, 7 weekdays (Sunday
                 first), 7 short weekdays, AM, PM, short date pattern, first
                 day of the week ("0" = Sunday) in its likeliest region
  then "", then region overrides: "en-GB", pattern, first day, …
Patterns are in base::formatCivil's syntax: CLDR's "y" becomes "yyyy".
"""
import os
import sys

from babel import Locale, __version__ as babel_version
from babel.core import get_global

# The languages people are likely to run msga under (en and ja are built
# into base/time.cpp on every OS).
LANGUAGES = [
    'de', 'es', 'fr', 'it', 'nl', 'pt', 'sv', 'da', 'nb', 'fi', 'pl', 'cs',
    'hu', 'ro', 'el', 'tr', 'ru', 'uk', 'ko', 'zh', 'hi', 'id', 'vi', 'th',
    'he', 'ar',
]
# Regions whose short date differs from their language's default.
REGIONS = [
    'en_GB', 'en_AU', 'en_CA', 'en_IE', 'en_IN', 'en_NZ', 'en_ZA', 'en_SG',
    'en_DE', 'en_SE', 'en_NL', 'en_DK', 'en_FI', 'en_CH', 'en_BE', 'en_AT',
    'de_AT', 'de_CH', 'fr_CA', 'fr_CH', 'fr_BE', 'it_CH', 'nl_BE', 'pt_PT',
    'es_MX', 'es_AR', 'es_US', 'es_CO', 'es_CL', 'zh_TW', 'zh_HK', 'sv_FI',
    'en_US', 'ar_SA', 'ar_AE', 'ar_MA', 'fr_CA', 'de_DE', 'nl_NL',
]


def civil_pattern(cldr):
    out, i = [], 0
    while i < len(cldr):
        c = cldr[i]
        if c == "'":  # quoted literal: kept as is
            j = cldr.find("'", i + 1)
            j = len(cldr) - 1 if j < 0 else j
            out.append(cldr[i:j + 1])
            i = j + 1
            continue
        n = 1
        while i + n < len(cldr) and cldr[i + n] == c:
            n += 1
        out.append('yyyy' if c == 'y' and n != 2 else c * n)
        i += n
    return ''.join(out)


def names(loc):
    m = loc.months['format']
    d = loc.days['format']
    periods = loc.day_periods['format']['abbreviated']
    days = lambda w: [w[6]] + [w[i] for i in range(6)]  # Babel: 0 = Monday
    return ([m['wide'][i] for i in range(1, 13)] +
            [m['abbreviated'][i] for i in range(1, 13)] +
            days(d['wide']) + days(d['abbreviated']) +
            [periods['am'], periods['pm']])


def likeliest(code):
    return Locale.parse(get_global('likely_subtags').get(code, code))


def first_day(loc):
    return str((loc.first_week_day + 1) % 7)  # Babel: 0 = Monday


def c_literal(s):
    out = []
    for b in s.encode('utf-8'):
        if b == 0x22 or b == 0x5C:
            out.append('\\' + chr(b))
        elif 0x20 <= b < 0x7F:
            out.append(chr(b))
        else:
            out.append('\\%03o' % b)
    return ''.join(out)


def main():
    parts = []
    for code in LANGUAGES:
        loc = Locale.parse(code)
        fields = ([code] + names(loc) + [civil_pattern(loc.date_formats['short'].pattern)] +
                  [first_day(likeliest(code))])
        assert all('\0' not in f and f for f in fields), code
        parts.append(fields)
    overrides = []
    for tag in REGIONS:
        lang = tag.split('_')[0]
        base = likeliest(lang)
        loc = Locale.parse(tag)
        pat = loc.date_formats['short'].pattern
        if lang == 'en' or pat != base.date_formats['short'].pattern or \
                loc.first_week_day != base.first_week_day:
            overrides.append([tag.replace('_', '-'), civil_pattern(pat), first_day(loc)])

    lines = [
        '// Generated by src/tools/date_locales.py from CLDR (Babel %s). Do not edit.'
        % babel_version,
        '// Per language: code, 12 months, 12 short months, 7 weekdays, 7 short',
        '// weekdays (Sunday first), AM, PM, short date, first weekday ("0" =',
        '// Sunday); "" ends the list; then region overrides: tag, pattern, first day.',
        'static const char kDateLocales[] =',
    ]
    for fields in parts + [['']] + overrides:
        lines.append('    "%s\\0"' % '\\0"\n    "'.join(c_literal(f) for f in fields))
    lines[-1] += ';'
    lines.append('constexpr int kDateLocaleFields = %d; // after the code' % (len(parts[0]) - 1))
    out = os.path.join(os.path.dirname(__file__), '..', 'base', 'date_locales_generated.inc')
    with open(out, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines) + '\n')
    print('wrote %s: %d languages, %d region overrides' % (out, len(parts), len(overrides)))


if __name__ == '__main__':
    sys.exit(main())
